### ISSUE TITLE
Navbar Links Not Functioning Properly

### ISSUE THREAD

**Issue by imkool47** [imkool47/myportfolio-website#3]
Issue Description:
The navbar on the portfolio website is not functioning as expected. Specifically, the following issues have been observed:

1; Navigation Links: Some or all of the navigation links in the navbar are not correctly routing to the intended sections of the website.

2; Responsive Design: The navbar might not be displaying properly on different screen sizes, particularly on mobile devices.

3; Active Link Highlighting: The active link is not being highlighted as expected, leading to a poor user experience.

**Comment by shubhamc1947** [comment]
@imkool47  can you assign this task to me .

**Comment by imkool47** [comment]
@shubhamc1947 This issue is assign to you.
